config/routes.rb
Rails.application.routes.draw do
  resources :encomendas

  devise_for :normal_users
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :categories

  resources :products

  root 'main#index'
  match "produto/:id" => "main#show", as: :main_produto, via: :get
  match "search" => "main#search", as: :search, via: :get
  match "search_results" => "main#search_results", as: :search_results, via: :post
  match "categoria/:categoria" => "main#categoria", as: :categoria, via: :get

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/category.rb
class Category < ActiveRecord::Base

	has_many :products
end

app/models/encomenda.rb
class Encomenda < ActiveRecord::Base


end

app/models/normal_user.rb
class NormalUser < ActiveRecord::Base

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/product.rb
class Product < ActiveRecord::Base

belongs_to :category

has_attached_file :image, :styles => { :small  => "150x150>", :medium  => "300x300>"},
				  :url => "/assets/images/:id/:style/:basename.:extension",
				  :path => ":rails_root/public/assets/images/:id/:style/:basename.:extension"



#do_not_validate_attachment_file_type :image
validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/
#validates_attachment_presence :image
#validates_attachment_size :image, :less_than => 5.megabytes
#validates_attachment_content_type :image, :content_type => ['image/jpeg', 'image/png']

validates :description, :name, :price, :presence=> true
validates :price, :numericality => true

end

#,
#				  :url => "/assets/images/:id/:style/:basename.:extension",
#				  :path => ":rails_root/public/assets/images/:id/:style/:basename.:extension"

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  
  #protect_from_forgery with: :exception
  before_filter :set_categ


  def set_categ
    @categoriesNav ||= ::Category.order(:name)
  end
 
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:name, :description)
    end
end

app/controllers/encomendas_controller.rb
class EncomendasController < InheritedResources::Base

	before_filter :authenticate_normal_user!


  private

    def encomenda_params
      params.require(:encomenda).permit(:endereco, :cartao_credito, :comprador)
    end
end

app/controllers/login_controller.rb
class LoginController < ApplicationController
  def index
  end
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  def index
  	@products = Product.order(:name)
    @categorias = Category.order(:name)
  end

  def show
  	@product = Product.find(params[:id])
  end

  def search 

  end 

  def search_results
    #@products = Product.where(:name => params[:keywords])
    @products = Product.where("name LIKE ?", "%#{params[:keywords]}%")
  end
    def categoria
    @products = Product.where(:category_id => params[:categoria])
  end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json
  def index
    @products = Product.all
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
    @categories = Category.order(:name)
  end

  # GET /products/1/edit
  def edit
    @categories = Category.order(:name)
  end

  # POST /products
  # POST /products.json

    def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end 

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name, :price, :description, :image, :category_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/encomendas_helper.rb
module EncomendasHelper
end

app/helpers/login_helper.rb
module LoginHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/categories/_form.html.erb
<%= form_for @category, :html => { :class => "form-horizontal category" } do |f| %>

  <% if @category.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@category.errors.count, "error") %> prohibited this category from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @category.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :name, :class => 'form-control' %>
    </div>
    <%=f.error_span(:name) %>
  </div>
  <div class="form-group">
    <%= f.label :description, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :description, :class => 'form-control' %>
    </div>
    <%=f.error_span(:description) %>
  </div>

  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                categories_path, :class => 'btn btn-default' %>
    </div>
  </div>

<% end %>

app/views/categories/edit.html.erb
<%- model_class = Category -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/categories/index.html.erb
<%- model_class = Category -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:description) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @categories.each do |category| %>
      <tr>
        <td><%= link_to category.id, category_path(category) %></td>
        <td><%= category.name %></td>
        <td><%= category.description %></td>
        <td><%=l category.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_category_path(category), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      category_path(category),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_category_path,
            :class => 'btn btn-primary' %>

app/views/categories/new.html.erb
<%- model_class = Category -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/categories/show.html.erb
<%- model_class = Category -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @category.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:description) %>:</strong></dt>
  <dd><%= @category.description %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              categories_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_category_path(@category), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              category_path(@category),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>

app/views/encomendas/_form.html.erb
<%= form_for(@encomenda) do |f| %>
  <% if @encomenda.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@encomenda.errors.count, "error") %> prohibited this encomenda from being saved:</h2>

      <ul>
      <% @encomenda.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :endereco %><br>
    <%= f.text_field :endereco %>
  </div>
  <div class="field">
    <%= f.label :cartao_credito %><br>
    <%= f.text_field :cartao_credito %>
  </div>
    
 <!--   <%#= current_normal_user.email :cliente %> -->

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/encomendas/edit.html.erb
<h1>Editing encomenda</h1>

<%= render 'form' %>

<%= link_to 'Show', @encomenda %> |
<%= link_to 'Back', encomendas_path %>

app/views/encomendas/index.html.erb
<h1>Listing encomendas</h1>

<table>
  <thead>
    <tr>
      <th>Endereco</th>
      <th>Cartao credito</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @encomendas.each do |encomenda| %>
      <tr>
        <td><%= encomenda.endereco %></td>
        <td><%= encomenda.cartao_credito %></td>
        <td><%= link_to 'Show', encomenda %></td>
        <td><%= link_to 'Edit', edit_encomenda_path(encomenda) %></td>
        <td><%= link_to 'Destroy', encomenda, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Encomenda', new_encomenda_path %>

app/views/encomendas/new.html.erb
<h1> Encomenda</h1>

<%= render 'form' %>

app/views/encomendas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Endereco:</strong>
  <%= @encomenda.endereco %>
</p>

<p>
  <strong>Cartao credito:</strong>
  <%= @encomenda.cartao_credito %>
</p>

<%= link_to 'Edit', edit_encomenda_path(@encomenda) %> |
<%= link_to 'Back', encomendas_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>LojaWeb</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

 <!-- Google font -->
<link href='http://fonts.googleapis.com/css?family=Open+Sans' rel='stylesheet' type='text/css'>

</head>
<body>



  <% flash.each do |key, value| %>
      <div class="alert alert-<%= key %> alert-dismissable">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
        <%= value %>
      </div>
  <% end %>


<div class="navbar navbar-default navbar-fixed-top" role="navigation">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand"> LojaAlexandre </a>
      </div>
      <div class="navbar-collapse collapse">
        <ul class="nav navbar-nav navbar-right">

         <li class="active"><%= link_to "Inicio", root_path %></li>
         <li> <%= link_to "Busca", search_path %></li>
          <li><a href="#about" data-toggle="modal">Sobre</a></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">Categorias <b class="caret"></b></a>
            <ul class="dropdown-menu">
        <!--      <li class="dropdown-header">Produtos Eletronicos</li>
              <li><a href="#">Computadores</a></li>
              <li><a href="#">Tablets</a></li>
              <li class="divider"></li>
              <li class="dropdown-header">Produtos de casa</li>
              <li><a href="#">Geladeira</a></li>
              <li><a href="#">Fogao</a></li> -->
              <li class="dropdown-header">Categorias</li>
              <% @categoriesNav.each do |c| %>
              <li><a> <%= link_to c.name, categoria_path(c) %></a> </li>
              <% end %>

            </ul>
          </li>
        <li><a href="#contact" data-toggle="modal">Contato</a></li>
        <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown"> Area Usuario<b class="caret"></b></a>
            <ul class="dropdown-menu">

              <li class="dropdown-header">Admin</li>
        <li><%= link_to "Cadastro Produtos", products_path %></li>
        <li><%= link_to "Cadastro Categorias", categories_path %></li>
            </ul>

          </li>

          <% if normal_user_signed_in? %>
            Signed in as <%= current_normal_user.email %>.
            <%= link_to "Sign out", destroy_normal_user_session_path, :method => :delete %>
            <% else %>
            <%= link_to "Sign up", new_normal_user_registration_path %> or <%= link_to "sign in", new_normal_user_session_path %>
            <% end %>

      </ul>
    </div><!--/.nav-collapse -->
  </div>
</div>


<div class="navbar navbar-inverse navbar-fixed-bottom" role="navigation">
	<div class="container">
		<div class="navbar-text pull-left">
			<p>© 2014 Loja Alexandre.</p>
		</div>
		<div class="navbar-text pull-right">
			<a href="#"><i class="fa fa-facebook-square fa-2x"></i></a>
		</div>
	</div>
</div>


 <!-- Bootstrap core JavaScript
================================================== -->
<!-- Mensagens -->
<div class="modal fade" id="contact" role="dialog">
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header">
				<h4>Contato<h4>
			</div>
			<div class="modal-body">
				<p>Mande um e-mail para alexandrekry@gmail.com</p>
			</div>
			<div class="modal-footer">
				<a class="btn btn-primary" data-dismiss="modal">Close</a>
			</div>
		</div>
	</div>
</div>


<div class="modal fade" id="about" role="dialog">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h4>Sobre<h4>
      </div>
      <div class="modal-body">
        <p>Site criado para o projeto de Orientação a Objetos</p>
        <p>Unb FGA</p>
      </div>
      <div class="modal-footer">
        <a class="btn btn-primary" data-dismiss="modal">Close</a>
      </div>
    </div>
  </div>
</div>

  <div class="container">

 <!-- 
================================================== -->
<!-- Mensagens END-->

    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
    <!-- Include all compiled plugins (below), or include individual files as needed -->
    <script src="js/bootstrap.min.js"></script>
  </body>
</html>


<%= yield %>
</div>

 <!-- 
================================================== -->
<!-- Mensagens END-->

    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
    <!-- Include all compiled plugins (below), or include individual files as needed -->
    <script src="js/bootstrap.min.js"></script>
  </body>
</html>

</body>
</html>

app/views/main/categoria.html.erb
<h2>Produtos da Categoria</h2>

<% if @products.empty? %>
	<p>Não foi encontrado nenhum produto dessa Categoria </p>
	<!--seguranca CSS(se colocar raw antes dos params)  <script> alert("A");</script>   -->
	<%end%>
  <div class="row">
    <% @products.each do |p| %>
      <div class="col-sm-3 text-center">
        <div class="panel panel-default">
            <div class="panel-body">
              <p> 
              <p><h4><%= p.name %></h4></p>
              <a href="#" class="thumbnail">
              <%= image_tag p.image %>
              </a>
              <p> <%= p.description %></p> 
              <p> R<%= number_to_currency(p.price) %> </p>
              <a href="#" class="btn btn-danger"> Comprar</a>
              <%= link_to  "Detalhes", main_produto_path( p), :class => 'btn btn-primary' %> 
              </p>
            </div>
        </div>
     </div>
    <% end %>
  </div>

  <%= link_to  "Voltar", root_path, :class => 'btn btn-success' %> 

app/views/main/index.html.erb
<!DOCTYPE html>


<!--
	<div class="container">
<div class="jumbotron text-center">
<h2>Promocoes</h2>
<p>Compre e ganhe 20% de desconto</p>
</div>
-->
      <div id="myCarousel" class="carousel slide" data-ride="carousel" data-interval = "3000">
        <!-- Indicators -->
        <ol class="carousel-indicators">
          <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
          <li data-target="#myCarousel" data-slide-to="1"></li>
          <li data-target="#myCarousel" data-slide-to="2"></li>
        </ol>
       
        <!-- Wrapper for slides -->
        <div class="carousel-inner">
          <div class="item active">
            <img src= "<%= asset_path('smartphones.png') %>" alt="..." class ="img-responsive">
            <div class="carousel-caption">
                <h3>Promoções</h3>
            </div>
          </div>
          <div class="item">
            <img src="<%= asset_path('smartphones.png') %>" alt="...">
       <     <div class="carousel-caption">
                <h3>Promoções</h3>
            </div>
          </div>
          <div class="item">
            <img src="<%= asset_path('smartphones.png') %>" alt="...">
            <div class="carousel-caption">
                <h3>Promoções</h3>
            </div>
          </div>
        </div>
       
        <!-- Controls -->
        <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
          <span class="glyphicon glyphicon-chevron-left"></span>
        </a>
        <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
          <span class="glyphicon glyphicon-chevron-right"></span>
        </a>
      </div> <!-- Carousel -->

    <div class="conteudo">

  <div class="row">

  <div class ="col-sm-2">
<div class="panel panel-default pull-left text-center">
  <!-- Default panel contents -->
  <div class="panel-heading"><h3> Categorias</h3></div>
  <ul class="list-group">
          <% @categorias.each do |c| %>
             <li class="list-group-item"><h4> <%= link_to c.name, categoria_path(c) %> </h4></li>
          <% end %>
  </ul>
</div>
</div>

        <div class="col-sm-10 text-center">
    <% @products.each do |p| %>
      <div class="col-sm-4 text-center">
        <div class="panel panel-default">
            <div class="panel-body">
              <p>
              <p><h4><%= p.name %></h4></p>
            <!--  <a href="#" class="thumbnail"> -->
                  <a class="thumbnail" width = "100%">
              <%= image_tag p.image %>
              </a>
              <p> <%= p.description %></p> 
              <p> R<%= number_to_currency(p.price) %> </p>
               <%= link_to  "Comprar", new_encomenda_path, :class => 'btn btn-danger' %> 
           <!--   <a  <  class="btn btn-primary"> Detalhes </a>  -->
              <%= link_to  "Detalhes", main_produto_path(p), :class => 'btn btn-primary' %> 
              </p>
            </div>
        </div>
     </div>
    <% end %>
  </div>


</div>


 <!-- Bootstrap core JavaScript
================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
<div class="modal fade" id="login" role="dialog">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h4>Login<h4>
      </div>
      <div class="modal-body">
        
<div class="input-group">
  <span class="input-group-addon"</span>
  <input type="text" class="form-control" placeholder="Username">
</div>

<div class="input-group">
  <span class="input-group-addon"</span>
  <input type="text" class="form-control" placeholder="Senha">
</div>

      <a href="#" class="btn btn-danger"> Login</a>
      <a href="#" class="btn btn-danger"> Logout</a>
      <a href="usuarios/new" class="btn btn-danger"> Cadastrar Usuario</a>

      </div>
      <div class="modal-footer">
        <a class="btn btn-primary" data-dismiss="modal">Close</a>
      </div>
    </div>
  </div>
</div>



 <!-- Bootstrap core JavaScript
================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
<div class="modal fade" id="produto" role="dialog">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h4>Nome<h4>
      </div>
      <div class="modal-body">
        
      </div>
      <div class="modal-footer">
        <a class="btn btn-primary" data-dismiss="modal">Close</a>
      </div>
    </div>
  </div>
</div>

app/views/main/search.html.erb
<h2>Buscar</h2>

	<%= form_tag search_results_path do %>

	<%= text_field_tag :keywords %>

	<%= submit_tag 'Search', :class => 'btn btn-primary' %>

	<% end %>

app/views/main/search_results.html.erb
<h2>Resultado da Busca</h2>

<% if @products.empty? %>
	<p>Não foi encontrado nenhum produto para '<%= params[:keywords] %>' </p>
	<!--seguranca CSS(se colocar raw antes dos params)  <script> alert("A");</script>   -->
	<%end%>
  <div class="row">
    <% @products.each do |p| %>
      <div class="col-sm-3 text-center">
        <div class="panel panel-default">
            <div class="panel-body">
              <p> 
              <p><h4><%= p.name %></h4></p>
              <a href="#" class="thumbnail">
              <%= image_tag p.image %>
              </a>
              <p> <%= p.description %></p> 
              <p> R<%= number_to_currency(p.price) %> </p>
              <a href="#" class="btn btn-danger"> Comprar</a>
              <%= link_to  "Detalhes", main_produto_path( p), :class => 'btn btn-primary' %> 
              </p>
            </div>
        </div>
     </div>
    <% end %>
  </div>

  <%= link_to  "Voltar", root_path, :class => 'btn btn-success' %> 

app/views/products/_product.html.erb
        <div class="panel panel-default">
            <div class="panel-body">
              <p>
              <p><h4><%= product.name %></h4></p>
              <a href="#" class="thumbnail">
              <%= image_tag product.image %>
              </a>
              <p> <%= product.description %></p> 
              <p> R<%= number_to_currency(product.price) %> </p>
              <a href="#" class="btn btn-danger"> Comprar</a>
           <!--   <a  <  class="btn btn-primary"> Detalhes </a>  -->
              <%= link_to  "Detalhes", main_produto_path(product), :class => 'btn btn-primary' %> 
              </p>
            </div>
        </div>

app/views/products/edit.html.erb
<%- model_class = Product -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/products/index.html.erb
<%- model_class = Product -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:price) %></th>
      <th><%= model_class.human_attribute_name(:description) %></th>

      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><%= link_to product.id, product_path(product) %></td>
        <td><%= product.name %></td>
        <td><%= product.price %></td>
        <td><%= product.description %></td>

        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_product_path(product), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      product_path(product),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_product_path,
            :class => 'btn btn-primary' %>